apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-portfolio
  namespace: flask-app-portfolio
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-app-portfolio
  template:
    metadata:
      labels:
        app: flask-app-portfolio
    spec:
      containers:
        - name: flask-app-portfolio
          image: zaid/flask-app-portfolio:7a9e11793a1fbcd5a66790b1c6116206d6e6e7d3
          ports:
            - containerPort: 5004
