apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-portfolio
  namespace: flask-app-portfolio
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-app-portfolio
  template:
    metadata:
      labels:
        app: flask-app-portfolio
    spec:
      containers:
        - name: flask-app-portfolio
          image: zaid/flask-app-portfolio:f704e647ede61848dd26f693aeb710f62f6f5885
          ports:
            - containerPort: 5004
