apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-recipe-backup-pvc
  namespace: my-recipe
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
