apiVersion: apps/v1
kind: Deployment
metadata:
  name: zen-ecommerce-backend
  namespace: zen-ecommerce
spec:
  replicas: 2
  selector:
    matchLabels:
      app: zen-ecommerce-backend
  template:
    metadata:
      labels:
        app: zen-ecommerce-backend
    spec:
      containers:
      - name: backend
        image: zaid/zen-ecommerce-backend:cb8e914036454022b04cc76528ba493893b8cd08
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
        - name: DB_HOST
          value: db

        - name: DB_PORT
          value: "5432"

        - name: DB_NAME
          value: ecommerce_db

        - name: DB_USER
          value: ecom_user

        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: zen-ecommerce-secrets
              key: db-password
        - name: ADMIN_EMAIL
          value: "admin@example.com"
        - name: ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: zen-ecommerce-secrets
              key: admin-password
