apiVersion: apps/v1
kind: Deployment
metadata:
  name: zen-ecommerce-frontend
  namespace: zen-ecommerce
spec:
  replicas: 2
  selector:
    matchLabels:
      app: zen-ecommerce-frontend
  template:
    metadata:
      labels:
        app: zen-ecommerce-frontend
    spec:
      containers:
      - name: frontend
        image: zaid/zen-ecommerce-frontend:411702958fca79bd2627331cac5978560dca6bac
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: NEXT_PUBLIC_API_URL
          value: "http://api.zen.lab"
