apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: zen-ecommerce

type: Opaque

stringData:
  POSTGRES_DB: ZWNvbW1lcmNlX2Ri
  POSTGRES_USER: ZWNvbV91c2Vy
  POSTGRES_PASSWORD: U3VwZXJTZWNyZXQxMjM=
