apiVersion: v1
kind: Service
metadata:
  name: my-recipe-app-service
  namespace: my-recipe-app
spec:
  type: NodePort
  selector:
    app: my-recipe-app
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30082
