apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: zen-ecommerce
type: Opaque
stringData:
  POSTGRES_DB: ecommerce_db
  POSTGRES_USER: ecom_user
  POSTGRES_PASSWORD: SuperSecret123
