name: Build and Push Flask Portfolio App

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "flask_app_portfolio/**"
      - "k8s-apps/flask_app_portfolio/**"
      - ".github/workflows/flask_app_portfolio.yml"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
           docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/flask-app-portfolio:${{ github.sha }} ./flask_app_portfolio

      - name: Push Docker image
        run: |
           docker push ${{ secrets.DOCKERHUB_USERNAME }}/flask-app-portfolio:${{ github.sha }}

      - name: Update Kubernetes manifest image tag
        run: |
          sed -i "s|image: zaid/flask-app-portfolio:.*|image: zaid/flask-app-portfolio:${{ github.sha }}|" k8s-apps/flask-app-portfolio/deployment.yaml

      - name: Commit updated image tag
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add k8s-apps/flask-app-portfolio/deployment.yaml
          git commit -m "Update Flask Portfolio image tag" || echo "No changes"
          git push
