name: Build and Deploy My Recipe App

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "my_recipe_app/**"
      - "k8s-apps/my_recipe_app/**"
      - ".github/workflows/my-recipe-app.yml"

permissions:
  contents: write

jobs:
  build-and-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/my-recipe-app:${{ github.sha }} ./my_recipe_app
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-recipe-app:${{ github.sha }}

      - name: Update Kubernetes manifest image tag
        run: |
          sed -i "s|image: .*/my-recipe-app:.*|image: ${{ secrets.DOCKERHUB_USERNAME }}/my-recipe-app:${{ github.sha }}|" k8s-apps/my_recipe_app/deployment.yaml

      - name: Commit updated manifest
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add k8s-apps/my_recipe_app/deployment.yaml
          git commit -m "Update my-recipe-app image to ${{ github.sha }}" || echo "No changes to commit"
          git push
